// @generated
// This file is @generated by prost-build.
/// Typed ShieldVault.sol events (one message per log we care about).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShieldEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<ShieldEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShieldEvent {
    #[prost(uint64, tag="1")]
    pub block: u64,
    #[prost(uint64, tag="2")]
    pub block_time: u64,
    #[prost(string, tag="3")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="4")]
    pub log_index: u32,
    /// authority address (lowercase hex)
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    /// Deposited, TopUpExecuted, RegistrationChanged, ...
    #[prost(string, tag="6")]
    pub name: ::prost::alloc::string::String,
    /// flat, stringly-typed fields so the schema is stable across versions
    #[prost(map="string, string", tag="7")]
    pub fields: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flow {
    #[prost(uint64, tag="1")]
    pub block: u64,
    #[prost(uint64, tag="2")]
    pub block_time: u64,
    #[prost(string, tag="3")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(enumeration="FlowKind", tag="5")]
    pub kind: i32,
    #[prost(bool, tag="6")]
    pub outbound: bool,
    #[prost(string, tag="7")]
    pub counterparty: ::prost::alloc::string::String,
    /// USDC base units (6 decimals)
    #[prost(uint64, tag="8")]
    pub amount: u64,
    #[prost(bool, tag="9")]
    pub counterparty_is_execution: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFlows {
    #[prost(message, repeated, tag="1")]
    pub flows: ::prost::alloc::vec::Vec<Flow>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BehavioralProfile {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub sent_to_execution: u64,
    #[prost(uint64, tag="3")]
    pub returned_from_execution: u64,
    #[prost(int64, tag="4")]
    pub net_execution_flow: i64,
    #[prost(uint64, tag="5")]
    pub deposited: u64,
    #[prost(uint64, tag="6")]
    pub top_up_count: u64,
    #[prost(uint64, tag="7")]
    pub return_count: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BehavioralProfiles {
    #[prost(message, repeated, tag="1")]
    pub profiles: ::prost::alloc::vec::Vec<BehavioralProfile>,
}
/// Money crossing the vault boundary: the behavioural memory.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FlowKind {
    Unspecified = 0,
    TopUpInstant = 1,
    TopUpGated = 2,
    ColdTransfer = 3,
    FullExit = 4,
    Return = 5,
    Deposit = 6,
}
impl FlowKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FlowKind::Unspecified => "FLOW_KIND_UNSPECIFIED",
            FlowKind::TopUpInstant => "TOP_UP_INSTANT",
            FlowKind::TopUpGated => "TOP_UP_GATED",
            FlowKind::ColdTransfer => "COLD_TRANSFER",
            FlowKind::FullExit => "FULL_EXIT",
            FlowKind::Return => "RETURN",
            FlowKind::Deposit => "DEPOSIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FLOW_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "TOP_UP_INSTANT" => Some(Self::TopUpInstant),
            "TOP_UP_GATED" => Some(Self::TopUpGated),
            "COLD_TRANSFER" => Some(Self::ColdTransfer),
            "FULL_EXIT" => Some(Self::FullExit),
            "RETURN" => Some(Self::Return),
            "DEPOSIT" => Some(Self::Deposit),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
