// @generated
// This file is @generated by prost-build.
// =====================================================================
// Decoded Shield vault program instructions — one message per instruction,
// args and named accounts decoded into typed fields (Anchor layout, see
// programs/shield-vault/src/lib.rs). Amounts are raw USDC (6 decimals).
// =====================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitializeVault {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub usdc_mint: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub vault_token_account: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub risk_verifier: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub protected_floor: u64,
    #[prost(uint32, tag="10")]
    pub top_up_threshold_bps: u32,
    #[prost(uint64, tag="11")]
    pub emergency_cap: u64,
    #[prost(uint64, tag="12")]
    pub velocity_threshold: u64,
    #[prost(uint64, tag="13")]
    pub loss_trigger_usdc: u64,
    #[prost(int64, tag="14")]
    pub loss_cooldown_secs: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Deposit {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub depositor: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub vault_token_account: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub source_token_account: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterOwner {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub owner: ::prost::alloc::string::String,
    /// 0 = execution, 1 = cold
    #[prost(uint32, tag="7")]
    pub kind: u32,
    #[prost(string, tag="8")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRegistration {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub registry_entry: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Tighten {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag="6")]
    pub new_protected_floor: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="7")]
    pub new_top_up_threshold_bps: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="8")]
    pub new_emergency_cap: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="9")]
    pub new_velocity_threshold: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="10")]
    pub new_loss_trigger_usdc: ::core::option::Option<u64>,
    #[prost(int64, optional, tag="11")]
    pub new_loss_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="12")]
    pub new_top_up_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="13")]
    pub new_loosen_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="14")]
    pub new_full_exit_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="15")]
    pub pause_top_ups_until: ::core::option::Option<i64>,
    #[prost(string, optional, tag="16")]
    pub set_risk_verifier: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeLoosen {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(uint64, optional, tag="7")]
    pub new_protected_floor: ::core::option::Option<u64>,
    #[prost(uint32, optional, tag="8")]
    pub new_top_up_threshold_bps: ::core::option::Option<u32>,
    #[prost(uint64, optional, tag="9")]
    pub new_emergency_cap: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="10")]
    pub new_velocity_threshold: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag="11")]
    pub new_loss_trigger_usdc: ::core::option::Option<u64>,
    #[prost(int64, optional, tag="12")]
    pub new_loss_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="13")]
    pub new_top_up_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="14")]
    pub new_loosen_cooldown_secs: ::core::option::Option<i64>,
    #[prost(int64, optional, tag="15")]
    pub new_full_exit_cooldown_secs: ::core::option::Option<i64>,
    #[prost(string, optional, tag="16")]
    pub new_risk_verifier: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag="17")]
    pub register_owner: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(uint32, tag="18")]
    pub register_kind: u32,
    #[prost(string, tag="19")]
    pub register_label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteRuleChange {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    /// set for execute_rule_change_with_registration
    #[prost(string, optional, tag="7")]
    pub registered_owner: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelProposal {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstantTopUp {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub vault_token_account: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub registry_entry: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub destination_token_account: ::prost::alloc::string::String,
    #[prost(uint64, tag="9")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeTopUp {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteTopUp {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub registry_entry: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub destination_token_account: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApplyRiskVerdict {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub relayer: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub nonce: u64,
    #[prost(int64, tag="7")]
    pub issued_at: i64,
    #[prost(int64, tag="8")]
    pub expiry: i64,
    #[prost(uint32, tag="9")]
    pub reason_code: u32,
    #[prost(uint64, tag="10")]
    pub realized_loss_usdc: u64,
    /// hex
    #[prost(string, tag="11")]
    pub evidence_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InstantColdTransfer {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub registry_entry: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub destination_token_account: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeColdTransferAboveCap {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposeUninstallVault {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub destination_owner: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteFullExit {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub proposal: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub registry_entry: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub destination_token_account: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShieldInstructions {
    #[prost(message, repeated, tag="1")]
    pub initialize_vaults: ::prost::alloc::vec::Vec<InitializeVault>,
    #[prost(message, repeated, tag="2")]
    pub deposits: ::prost::alloc::vec::Vec<Deposit>,
    #[prost(message, repeated, tag="3")]
    pub register_owners: ::prost::alloc::vec::Vec<RegisterOwner>,
    #[prost(message, repeated, tag="4")]
    pub remove_registrations: ::prost::alloc::vec::Vec<RemoveRegistration>,
    #[prost(message, repeated, tag="5")]
    pub tightens: ::prost::alloc::vec::Vec<Tighten>,
    #[prost(message, repeated, tag="6")]
    pub propose_loosens: ::prost::alloc::vec::Vec<ProposeLoosen>,
    #[prost(message, repeated, tag="7")]
    pub execute_rule_changes: ::prost::alloc::vec::Vec<ExecuteRuleChange>,
    #[prost(message, repeated, tag="8")]
    pub cancel_proposals: ::prost::alloc::vec::Vec<CancelProposal>,
    #[prost(message, repeated, tag="9")]
    pub instant_top_ups: ::prost::alloc::vec::Vec<InstantTopUp>,
    #[prost(message, repeated, tag="10")]
    pub propose_top_ups: ::prost::alloc::vec::Vec<ProposeTopUp>,
    #[prost(message, repeated, tag="11")]
    pub execute_top_ups: ::prost::alloc::vec::Vec<ExecuteTopUp>,
    #[prost(message, repeated, tag="12")]
    pub apply_risk_verdicts: ::prost::alloc::vec::Vec<ApplyRiskVerdict>,
    #[prost(message, repeated, tag="13")]
    pub instant_cold_transfers: ::prost::alloc::vec::Vec<InstantColdTransfer>,
    #[prost(message, repeated, tag="14")]
    pub propose_cold_transfers_above_cap: ::prost::alloc::vec::Vec<ProposeColdTransferAboveCap>,
    #[prost(message, repeated, tag="15")]
    pub propose_uninstall_vaults: ::prost::alloc::vec::Vec<ProposeUninstallVault>,
    #[prost(message, repeated, tag="16")]
    pub execute_full_exits: ::prost::alloc::vec::Vec<ExecuteFullExit>,
}
// =====================================================================
// Decoded Shield program events (Anchor `emit!`, "Program data:" logs) —
// one message per event, layouts from programs/shield-vault/src/events.rs.
// =====================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultInitializedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub authority: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub usdc_mint: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub protected_floor: u64,
    #[prost(uint64, tag="8")]
    pub velocity_threshold: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DepositedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub depositor: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(uint64, tag="7")]
    pub new_balance: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegistrationChangedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub owner: ::prost::alloc::string::String,
    #[prost(uint32, tag="6")]
    pub kind: u32,
    #[prost(bool, tag="7")]
    pub active: bool,
    #[prost(string, tag="8")]
    pub label: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PolicyTightenedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub config_version: u64,
    #[prost(int64, tag="6")]
    pub cooldown_until: i64,
    #[prost(uint64, tag="7")]
    pub protected_floor: u64,
    #[prost(uint64, tag="8")]
    pub velocity_threshold: u64,
    #[prost(uint32, tag="9")]
    pub top_up_threshold_bps: u32,
    #[prost(uint64, tag="10")]
    pub loss_trigger_usdc: u64,
    #[prost(int64, tag="11")]
    pub loss_cooldown_secs: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoosenProposedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    #[prost(int64, tag="6")]
    pub execute_after: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoosenExecutedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProposalCancelledEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint32, tag="5")]
    pub category: u32,
    #[prost(uint64, tag="6")]
    pub nonce: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopUpExecutedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(bool, tag="7")]
    pub instant: bool,
    #[prost(uint64, tag="8")]
    pub nonce: u64,
    #[prost(uint64, tag="9")]
    pub velocity_after: u64,
    #[prost(uint64, tag="10")]
    pub balance_after: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopUpProposedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(uint64, tag="7")]
    pub nonce: u64,
    #[prost(int64, tag="8")]
    pub execute_after: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ColdTransferExecutedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
    #[prost(bool, tag="7")]
    pub instant: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FullExitProposedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub nonce: u64,
    #[prost(int64, tag="7")]
    pub execute_after: i64,
    #[prost(bool, tag="8")]
    pub uninstall: bool,
    #[prost(uint64, tag="9")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FullExitExecutedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub destination_owner: ::prost::alloc::string::String,
    #[prost(uint64, tag="6")]
    pub amount: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RiskVerdictAppliedEvent {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub nonce: u64,
    #[prost(uint32, tag="6")]
    pub reason_code: u32,
    #[prost(uint64, tag="7")]
    pub realized_loss_usdc: u64,
    #[prost(int64, tag="8")]
    pub cooldown_until: i64,
    #[prost(bool, tag="9")]
    pub extended: bool,
    #[prost(string, tag="10")]
    pub evidence_hash: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ShieldEvents {
    #[prost(message, repeated, tag="1")]
    pub vault_initialized: ::prost::alloc::vec::Vec<VaultInitializedEvent>,
    #[prost(message, repeated, tag="2")]
    pub deposited: ::prost::alloc::vec::Vec<DepositedEvent>,
    #[prost(message, repeated, tag="3")]
    pub registration_changed: ::prost::alloc::vec::Vec<RegistrationChangedEvent>,
    #[prost(message, repeated, tag="4")]
    pub policy_tightened: ::prost::alloc::vec::Vec<PolicyTightenedEvent>,
    #[prost(message, repeated, tag="5")]
    pub loosen_proposed: ::prost::alloc::vec::Vec<LoosenProposedEvent>,
    #[prost(message, repeated, tag="6")]
    pub loosen_executed: ::prost::alloc::vec::Vec<LoosenExecutedEvent>,
    #[prost(message, repeated, tag="7")]
    pub proposal_cancelled: ::prost::alloc::vec::Vec<ProposalCancelledEvent>,
    #[prost(message, repeated, tag="8")]
    pub top_up_executed: ::prost::alloc::vec::Vec<TopUpExecutedEvent>,
    #[prost(message, repeated, tag="9")]
    pub top_up_proposed: ::prost::alloc::vec::Vec<TopUpProposedEvent>,
    #[prost(message, repeated, tag="10")]
    pub cold_transfer_executed: ::prost::alloc::vec::Vec<ColdTransferExecutedEvent>,
    #[prost(message, repeated, tag="11")]
    pub full_exit_proposed: ::prost::alloc::vec::Vec<FullExitProposedEvent>,
    #[prost(message, repeated, tag="12")]
    pub full_exit_executed: ::prost::alloc::vec::Vec<FullExitExecutedEvent>,
    #[prost(message, repeated, tag="13")]
    pub risk_verdict_applied: ::prost::alloc::vec::Vec<RiskVerdictAppliedEvent>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFlow {
    #[prost(uint64, tag="1")]
    pub slot: u64,
    #[prost(string, tag="2")]
    pub signature: ::prost::alloc::string::String,
    #[prost(int64, tag="3")]
    pub block_time: i64,
    #[prost(string, tag="4")]
    pub vault: ::prost::alloc::string::String,
    #[prost(enumeration="FlowKind", tag="5")]
    pub kind: i32,
    #[prost(bool, tag="6")]
    pub outbound: bool,
    /// owner pubkey (execution / cold wallet / depositor)
    #[prost(string, tag="7")]
    pub counterparty: ::prost::alloc::string::String,
    #[prost(uint64, tag="8")]
    pub amount: u64,
    #[prost(bool, tag="9")]
    pub counterparty_is_execution: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VaultFlows {
    #[prost(message, repeated, tag="1")]
    pub flows: ::prost::alloc::vec::Vec<VaultFlow>,
}
// =====================================================================
// Per-vault running behavioural totals (what the store keeps across the
// whole history). Windowed metrics (24h velocity, 7-day realized loss,
// loss streak, reload-after-loss) are derived by consumers from VaultFlows.
// =====================================================================

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionWalletTotals {
    #[prost(string, tag="1")]
    pub owner: ::prost::alloc::string::String,
    /// total USDC sent from the vault to this wallet
    #[prost(uint64, tag="2")]
    pub sent: u64,
    /// total USDC that came back from this wallet
    #[prost(uint64, tag="3")]
    pub returned: u64,
    /// returned - sent
    #[prost(int64, tag="4")]
    pub net_realized_flow: i64,
    #[prost(uint64, tag="5")]
    pub top_up_count: u64,
    #[prost(uint64, tag="6")]
    pub return_count: u64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BehavioralProfile {
    #[prost(string, tag="1")]
    pub vault: ::prost::alloc::string::String,
    #[prost(uint64, tag="2")]
    pub total_sent_to_execution: u64,
    #[prost(uint64, tag="3")]
    pub total_returned_from_execution: u64,
    #[prost(int64, tag="4")]
    pub net_realized_flow: i64,
    #[prost(uint64, tag="5")]
    pub total_deposited: u64,
    #[prost(uint64, tag="6")]
    pub total_exited: u64,
    #[prost(message, repeated, tag="7")]
    pub execution_wallets: ::prost::alloc::vec::Vec<ExecutionWalletTotals>,
    #[prost(uint64, tag="8")]
    pub last_updated_slot: u64,
    #[prost(int64, tag="9")]
    pub last_updated_at: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BehavioralProfiles {
    #[prost(message, repeated, tag="1")]
    pub profiles: ::prost::alloc::vec::Vec<BehavioralProfile>,
}
// =====================================================================
// Capital flows: every USDC movement across a vault's boundary, with the
// counterparty classified against the vault's own on-chain registry.
// Outflows come from Shield events; inflows are SPL Token transfers into
// a known vault token account (so returns from a trading venue that never
// calls Shield's `deposit` are still seen).
// =====================================================================

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FlowKind {
    Unspecified = 0,
    /// vault -> execution wallet, instant path
    TopUpInstant = 1,
    /// vault -> execution wallet, after the pause
    TopUpGated = 2,
    /// vault -> cold wallet (capped instant)
    ColdTransfer = 3,
    /// vault -> cold wallet (delayed exit)
    FullExit = 4,
    /// execution wallet -> vault (money coming back)
    Return = 5,
    /// anything else -> vault
    Deposit = 6,
}
impl FlowKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            FlowKind::Unspecified => "FLOW_KIND_UNSPECIFIED",
            FlowKind::TopUpInstant => "TOP_UP_INSTANT",
            FlowKind::TopUpGated => "TOP_UP_GATED",
            FlowKind::ColdTransfer => "COLD_TRANSFER",
            FlowKind::FullExit => "FULL_EXIT",
            FlowKind::Return => "RETURN",
            FlowKind::Deposit => "DEPOSIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FLOW_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "TOP_UP_INSTANT" => Some(Self::TopUpInstant),
            "TOP_UP_GATED" => Some(Self::TopUpGated),
            "COLD_TRANSFER" => Some(Self::ColdTransfer),
            "FULL_EXIT" => Some(Self::FullExit),
            "RETURN" => Some(Self::Return),
            "DEPOSIT" => Some(Self::Deposit),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
